# Generated by Django 4.2 on 2024-10-24 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statment', models.CharField(max_length=120)),
                ('document_type', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(max_length=1500)),
            ],
        ),
    ]
