# Generated by Django 4.2 on 2024-10-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0002_mail_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statment', models.CharField(max_length=120)),
                ('document_type', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(max_length=1500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
